@echo off
echo Installing dependencies...
npm install
echo Generating prisma client...
npm run prisma:migrate
echo Registering commands...
npm run commands:register
echo Compiling...
npm run build
echo Bot is ready to deploy. Use `npm start` to launch.
pause